version: "2"

services:
  db:
    image: "mariadb:latest"
    volumes:
      - "~/mariadb_data:/var/lib/mysql"
    restart: "always"
    environment:
      MARIADB_ROOT_PASSWORD: "password"
      MARIADB_DATABASE: "test"
      MARIADB_USER: "user"
      MARIADB_PASSWORD: "password"
    ports:
      - "3306:3306"
    expose:
      - "3306"
  event-tracker:
    volumes:
      - "~/cert:/tmp/cert"
    privileged: true
    build: .
    image: "event-tracker:latest"
    depends_on:
      - "db"
    restart: "always"
    environment:
      DOMAIN: "www.makeshift.dev"
      USE_AUTOCERT: "true"
      DB_USER: "user"
      DB_PASSWORD: "password"
      DB_NAME: "test"
      DB_PORT: 3306
      HTTP_PORT: 80
      HTTPS_PORT: 443
      GITHUB_SECRET: "secret"
      SLACK_SIGNING_SECRET: "secret"
    ports:
      - "443:443"
      - "80:80"
